# Multi-checkout sample pipeline
# official documentation: https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/multi-repo-checkout?view=azure-devops

resources:
  repositories:
  - repository: repository_identifier
    type: git
    name: project/repository_name #if in the same repo can be just name of the repository
    ref: refs/heads/main

jobs:  
- job: job_name
  pool:
    vmImage: ubuntu-latest
  steps:
    - checkout: self  # will checkout current repository
      path: this-repo # relative path where to check out source code, will be '$(Agent.BuildDirectory)/this-repo'

    - checkout: repository_identifier
      path: other-repo

    - task: PowerShell@2
      inputs:
        filePath: '$(Agent.BuildDirectory)/other-repo/relative-path-in-repo/script.ps1'
        failOnStderr: true
        showWarnings: true
        pwsh: true
        workingDirectory: '$(Agent.BuildDirectory)/backstage-catalog-components/pipelines'
